const sfSymbols = [
    { sf: "square.and.arrow.up.fill", material: "share", matchQuality: "ok" },
    { sf: "highlighter", material: "border_color", matchQuality: "ok" },
    { sf: "pencil.tip", material: "stylus_pencil", matchQuality: "ok" },
    { sf: "trash.fill", material: "delete", matchQuality: "ok" },
    { sf: "folder.fill", material: "folder", matchQuality: "ok" },
    { sf: "paperplane.fill", material: "send", matchQuality: "ok" },
    { sf: "tray.fill", material: "inbox", matchQuality: "ok" },
    { sf: "externaldrive.fill", material: "hard_drive", matchQuality: "ok" },
    { sf: "archivebox.fill", material: "inventory_2", matchQuality: "ok" },
    { sf: "doc.text.fill", material: "description", matchQuality: "ok" },
    { sf: "doc.fill", material: "draft", matchQuality: "ok" },
    { sf: "terminal.fill", material: "terminal", matchQuality: "ok" },
    { sf: "arrowshape.turn.up.left.fill", material: "line_start_arrow", matchQuality: "ok" },
    { sf: "arrowshape.turn.up.right.fill", material: "line_end_arrow", matchQuality: "ok" },
    { sf: "book.fill", material: "auto_stories", matchQuality: "ok" },
    { sf: "book.closed.fill", material: "book_2", matchQuality: "ok" },
    { sf: "books.vertical.fill", material: "library_books", matchQuality: "ok" },
    { sf: "bookmark.fill", material: "bookmark", matchQuality: "ok" },
    { sf: "graduationcap.fill", material: "school", matchQuality: "ok" },
    { sf: "ticket.fill", material: "local_activity", matchQuality: "ok" },
    { sf: "paperclip", material: "attach_file", matchQuality: "ok" },
    { sf: "link", material: "link", matchQuality: "ok" },
    { sf: "person.fill", material: "person", matchQuality: "ok" },
    { sf: "person.2.fill", material: "group", matchQuality: "ok" },
    { sf: "command", material: "keyboard_command_key", matchQuality: "ok" },
    { sf: "power", material: "power_settings_new", matchQuality: "ok" },
    { sf: "globe", material: "language", matchQuality: "ok" },
    { sf: "powersleep", material: "bedtime", matchQuality: "ok" },
    { sf: "moon.fill", material: "nightlight", matchQuality: "ok" },
    { sf: "moon.zzz.fill", material: "nights_stay", matchQuality: "ok" },
    { sf: "sun.max.fill", material: "light_mode", matchQuality: "ok" },
    { sf: "sparkles", material: "auto_awesome", matchQuality: "ok" },
    { sf: "umbrella.fill", material: "umbrella", matchQuality: "ok" },
    { sf: "cloud.fill", material: "cloud", matchQuality: "ok" },
    { sf: "flame.fill", material: "local_fire_department", matchQuality: "ok" },
    { sf: "exclamationmark.triangle.fill", material: "warning", matchQuality: "ok" },
    { sf: "play.circle.fill", material: "play_circle", matchQuality: "ok" },
    { sf: "drop.fill", material: "water_drop", matchQuality: "ok" },
    { sf: "speaker.wave.2.fill", material: "volume_up", matchQuality: "ok" },
    { sf: "magnifyingglass", material: "search", matchQuality: "ok" },
    { sf: "megaphone.fill", material: "campaign", matchQuality: "ok" },
    { sf: "mic.fill", material: "mic", matchQuality: "ok" },
    { sf: "suit.heart.fill", material: "favorite", matchQuality: "ok" },
    { sf: "star.square.fill", material: "stars", matchQuality: "ok" },
    { sf: "star.fill", material: "star", matchQuality: "ok" },
    { sf: "flag.fill", material: "flag", matchQuality: "ok" },
    { sf: "location.fill", material: "near_me", matchQuality: "ok" },
    { sf: "bell.fill", material: "notifications", matchQuality: "ok" },
    { sf: "tag.fill", material: "local_offer", matchQuality: "ok" },
    { sf: "bolt.fill", material: "flash_on", matchQuality: "ok" },
    { sf: "bolt.batteryblock.fill", material: "battery_charging_full", matchQuality: "ok" },
    { sf: "eyes", material: "remove_red_eye", matchQuality: "ok" },
    { sf: "eyes.fill", material: "face", matchQuality: "ok" },
    { sf: "eyes.inverse", material: "face_2", matchQuality: "ok" },
    { sf: "mustache.fill", material: "face_5", matchQuality: "ok" },
    { sf: "eyeglasses", material: "eyeglasses", matchQuality: "ok" },
    { sf: "brain", material: "neurology", matchQuality: "ok" },
    { sf: "flashlight.off.fill", material: "flashlight_on", matchQuality: "ok" },
    { sf: "camera.fill", material: "photo_camera", matchQuality: "ok" },
    { sf: "message.fill", material: "message", matchQuality: "ok" },
    { sf: "bubble.right.fill", material: "chat_bubble", matchQuality: "ok" },
    { sf: "quote.opening", material: "format_quote", matchQuality: "ok" },
    { sf: "phone.fill", material: "phone", matchQuality: "ok" },
    { sf: "video.fill", material: "videocam", matchQuality: "ok" },
    { sf: "envelope.fill", material: "mail", matchQuality: "ok" },
    { sf: "gear", material: "tune", matchQuality: "ok" },
    { sf: "gearshape.fill", material: "settings", matchQuality: "ok" },
    { sf: "dice.fill", material: "casino", matchQuality: "ok" },
    { sf: "scissors", material: "content_cut", matchQuality: "ok" },
    { sf: "bag.fill", material: "shopping_bag", matchQuality: "ok" },
    { sf: "cart.fill", material: "shopping_cart", matchQuality: "ok" },
    { sf: "theatermasks.fill", material: "theater_comedy", matchQuality: "ok" },
    { sf: "car.fill", material: "directions_car", matchQuality: "ok" },
    { sf: "motorcycle.custom", material: "motorcycle", matchQuality: "ok" },
    { sf: "bicycle", material: "pedal_bike", matchQuality: "ok" },
    { sf: "creditcard.fill", material: "credit_card", matchQuality: "ok" },
    { sf: "gift.fill", material: "featured_seasonal_and_gifts", matchQuality: "ok" },
    { sf: "giftcard.fill", material: "card_giftcard", matchQuality: "ok" },
    { sf: "gyroscope", material: "360", matchQuality: "ok" },
    { sf: "pianokeys.inverse", material: "piano", matchQuality: "ok" },
    { sf: "speedometer", material: "speed", matchQuality: "ok" },
    { sf: "wand.and.stars", material: "auto_fix_high", matchQuality: "ok" },
    { sf: "paintbrush.fill", material: "format_paint", matchQuality: "ok" },
    { sf: "paintbrush.pointed.fill", material: "brush", matchQuality: "ok" },
    { sf: "bandage.fill", material: "healing", matchQuality: "ok" },
    { sf: "wrench.fill", material: "build", matchQuality: "ok" },
    { sf: "ruler.fill", material: "straighten", matchQuality: "ok" },
    { sf: "hammer.fill", material: "hardware", matchQuality: "ok" },
    { sf: "printer.fill", material: "print", matchQuality: "ok" },
    { sf: "applescript.fill", material: "contract", matchQuality: "ok" },
    { sf: "cross.case.fill", material: "medical_services", matchQuality: "ok" },
    { sf: "briefcase.fill", material: "business_center", matchQuality: "ok" },
    { sf: "case.fill", material: "work", matchQuality: "ok" },
    { sf: "puzzlepiece.fill", material: "extension", matchQuality: "ok" },
    { sf: "building.columns.fill", material: "account_balance", matchQuality: "ok" },
    { sf: "house.fill", material: "home", matchQuality: "ok" },
    { sf: "lock.fill", material: "lock", matchQuality: "ok" },
    { sf: "lock.open.fill", material: "lock_open", matchQuality: "ok" },
    { sf: "key.fill", material: "key", matchQuality: "ok" },
    { sf: "pin.fill", material: "push_pin", matchQuality: "ok" },
    { sf: "map.fill", material: "map", matchQuality: "ok" },
    { sf: "safari.fill", material: "explore", matchQuality: "ok" },
    { sf: "cpu.fill", material: "memory", matchQuality: "ok" },
    { sf: "desktopcomputer", material: "desktop_windows", matchQuality: "ok" },
    { sf: "laptopcomputer", material: "laptop", matchQuality: "ok" },
    { sf: "iphone", material: "smartphone", matchQuality: "ok" },
    { sf: "tv.inset.filled", material: "tv_gen", matchQuality: "ok" },
    { sf: "radio.fill", material: "radio", matchQuality: "ok" },
    { sf: "film", material: "theaters", matchQuality: "ok" },
    { sf: "bus.fill", material: "directions_bus", matchQuality: "ok" },
    { sf: "airplane", material: "flight", matchQuality: "ok" },
    { sf: "scooter", material: "scooter", matchQuality: "ok" },
    { sf: "leaf.fill", material: "eco", matchQuality: "ok" },
    { sf: "camera.macro", material: "psychiatry", matchQuality: "ok" },
    { sf: "face.smiling.fill", material: "sentiment_very_satisfied", matchQuality: "ok" },
    { sf: "fuelpump.fill", material: "local_gas_station", matchQuality: "ok" },
    { sf: "crown.fill", material: "crown", matchQuality: "ok" },
    { sf: "shield.fill", material: "shield", matchQuality: "ok" },
    { sf: "photo.fill", material: "photo", matchQuality: "ok" },
    { sf: "bed.double.fill", material: "bed", matchQuality: "ok" },
    { sf: "pills.fill", material: "pill", matchQuality: "ok" },
    { sf: "cross.vial.fill", material: "medication", matchQuality: "ok" },
    { sf: "hare.fill", material: "cruelty_free", matchQuality: "ok" },
    { sf: "tortoise.fill", material: "pest_control", matchQuality: "ok" },
    { sf: "shippingbox.fill", material: "package_2", matchQuality: "ok" },
    { sf: "clock.fill", material: "access_time", matchQuality: "ok" },
    { sf: "alarm.fill", material: "alarm", matchQuality: "ok" },
    { sf: "gamecontroller.fill", material: "sports_esports", matchQuality: "ok" },
    { sf: "paintpalette.fill", material: "palette", matchQuality: "ok" },
    { sf: "figure.walk", material: "directions_walk", matchQuality: "ok" },
    { sf: "figure.stand", material: "accessibility", matchQuality: "ok" },
    { sf: "pawprint.fill", material: "pets", matchQuality: "ok" },
    { sf: "ladybug.fill", material: "bug_report", matchQuality: "ok" },
    { sf: "ferry.fill", material: "directions_boat", matchQuality: "ok" },
    { sf: "music.note", material: "music_note", matchQuality: "ok" },
    { sf: "hand.raised.fill", material: "back_hand", matchQuality: "ok" },
    { sf: "chart.pie.fill", material: "pie_chart", matchQuality: "ok" },
    { sf: "hourglass", material: "hourglass_bottom", matchQuality: "ok" },
    { sf: "touchid", material: "fingerprint", matchQuality: "ok" },
    { sf: "lightbulb.fill", material: "lightbulb", matchQuality: "ok" },
    { sf: "tshirt.fill", material: "laundry", matchQuality: "ok" },
    { sf: "cross.circle.fill", material: "local_hospital", matchQuality: "ok" },
    { sf: "snowflake", material: "ac_unit", matchQuality: "ok" },
    { sf: "fork.knife", material: "restaurant", matchQuality: "ok" },
    { sf: "burn", material: "clock_loader_60", matchQuality: "ok" },
    { sf: "figure.run", material: "directions_run", matchQuality: "ok" },
    { sf: "figure.skiing.downhill", material: "downhill_skiing", matchQuality: "ok" },
    { sf: "figure.martial.arts", material: "sports_martial_arts", matchQuality: "ok" },
    { sf: "dumbbell.fill", material: "fitness_center", matchQuality: "ok" },
    { sf: "medal.fill", material: "military_tech", matchQuality: "ok" },
    { sf: "trophy.fill", material: "emoji_events", matchQuality: "ok" },
    { sf: "football.fill", material: "sports_football", matchQuality: "ok" },
    { sf: "beach.umbrella.fill", material: "beach_access", matchQuality: "ok" },
    { sf: "balloon.fill", material: "celebration", matchQuality: "ok" },
    { sf: "wineglass.fill", material: "wine_bar", matchQuality: "ok" }
];

function generateIconComparison() {
    const materialList = document.querySelector('.material-icons-list');

    sfSymbols.forEach(icon => {
        const materialItem = document.createElement('div');
        materialItem.className = 'icon-item';
        materialItem.innerHTML = `
            <div class="icon-wrapper">
                <span class="material-icons">${icon.material}</span>
                <span class="match-indicator ${icon.matchQuality}"></span>
            </div>
            <div class="icon-names">
                <p class="sf-name">SF: ${icon.sf}</p>
                <p class="material-name">MD: ${icon.material}</p>
            </div>
        `;
        materialList.appendChild(materialItem);
    });
} 